version: '2'
services:
    wordpress:
        image: wordpress
        ports:
            - 8000:80
        environment:
            - WORDPRESS_DB_PASSWORD=root
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_NAME=test
        links:
            - mysql:mysql
        depends_on:
            - mysql
    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root  
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        links:
            - mysql:mysql
